// V7 thesis video carousel, robotics selector and optical measurement workflow.
document.querySelectorAll('[data-carousel]').forEach(car=>{let idx=0;const slides=[...car.querySelectorAll('.media-slide')];const label=car.parentElement.querySelector('.slide-index');function show(n){idx=(n+slides.length)%slides.length;slides.forEach((s,i)=>{s.classList.toggle('active',i===idx);s.setAttribute('aria-hidden',i===idx?'false':'true');const v=s.querySelector('video');if(v&&i!==idx)v.pause()});if(label)label.textContent=String(idx+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0')};car.querySelector('[data-prev]')?.addEventListener('click',()=>show(idx-1));car.querySelector('[data-next]')?.addEventListener('click',()=>show(idx+1));show(0)});
const sim={
 duobench:{src:'assets/robotics-duobench-clean.mp4',tag:'DUOBENCH · EXPERT REPLAY',title:'Bimanual cube transfer',prompt:'“Grasp the white cube with the right arm, hand it over to the left arm and place it in the white bowl with the left arm.”',description:'A successful simulator/controller expert demonstration provides a positive control for the FR3 Duo transfer task. It is not evidence of a learned-policy completion.'},
 additional:{src:'assets/robotics-additional.mp4',tag:'SINGLE-ARM MANIPULATION · VIDEO PROMPT',title:'Put the cube in the bowl',prompt:'“put the cube in the bowl”',description:'The prompt is visible in the source video. This separate single-arm example demonstrates goal-directed manipulation; it should not be confused with the FR3 Duo bimanual benchmark.'},
 libero:{src:'assets/robotics-libero.mp4',tag:'LIBERO · BENCHMARK SMOKE TEST',title:'Single-arm LIBERO test',prompt:'“Turn on Stove, and put the mocha pot on it.”',description:'A LIBERO manipulation clip used for inference/evaluation smoke testing. Its recorded visuals are not a measurement of FR3 Duo task success.'}
};const choice=document.getElementById('sim-choice');if(choice){function show(){const o=sim[choice.value];if(!o)return;const v=document.getElementById('selected-sim');v.pause();v.src=o.src;v.load();document.getElementById('sim-badge').textContent=o.tag;document.getElementById('sim-title').textContent=o.title;document.getElementById('sim-description').textContent=o.description;document.getElementById('sim-prompt').textContent=o.prompt;}choice.addEventListener('change',show);show()}
const steps=[
 ['A controlled light source','A xenon lamp feeds the optical measurement chain. The light source is stabilized before spectral scans, with light-tight enclosure and controlled illumination.'],
 ['Select the wavelength','The MSH-300 monochromator provides spectral selection across the measurement range. Slit settings and optical filters are chosen for the wavelength band.'],
 ['A PMT and a calibrated reference','Recovered ANTARES R7081-20 PMTs are measured alongside a calibrated silicon reference photodiode. A rotation stage supports angular-response studies.'],
 ['Automated precision readout','Keithley 6487 current readout and Python/PyVISA communication coordinate acquisitions, metadata, scan parameters and repeatable scans.'],
 ['Correct and verify','Dark-current baselines, stabilization, parameter readback and measurement uncertainties are handled before the derived quantum-efficiency calculation.'],
 ['Calculate quantum efficiency','Photodiode calibration, interpolated reference currents and the detector area ratio enter the PMT quantum-efficiency calculation for each measured wavelength.'],
 ['Population QC and spatial studies','Spectral features, outlier flags, PCA and angular-response analyses support a staged assessment of the recovered PMTs, including ST5937 spatial maps.']
];const buttons=[...document.querySelectorAll('[data-workstep]')];function workstep(n){const item=steps[n];if(!item)return;document.getElementById('workflow-title').textContent=item[0];document.getElementById('workflow-desc').textContent=item[1];document.getElementById('workflow-step-label').textContent=`STEP ${String(n+1).padStart(2,'0')} / 07`;buttons.forEach((b,i)=>{b.classList.toggle('active',i===n);b.setAttribute('aria-pressed',i===n?'true':'false')})}buttons.forEach(b=>b.addEventListener('click',()=>workstep(Number(b.dataset.workstep))));if(buttons.length)workstep(0);
